STOCKS = {
    "Adani Enterprises": "ADANIENT",
    "Adani Ports": "ADANIPORTS",
    "Ambuja Cements": "AMBUJACEM",
    "Apollo Hospitals": "APOLLOHOSP",
    "Asian Paints": "ASIANPAINT",
    "Avenue Supermarts (DMart)": "DMART",
    "Axis Bank": "AXISBANK",
    "Bajaj Auto": "BAJAJ-AUTO",
    "Bajaj Finance": "BAJFINANCE",
    "Bajaj Finserv": "BAJAJFINSV",
    "Bank of Baroda": "BANKBARODA",
    "Berger Paints": "BERGEPAINT",
    "Bharti Airtel": "BHARTIARTL",
    "BPCL": "BPCL",
    "Britannia": "BRITANNIA",
    "Canara Bank": "CANBK",
    "Cholamandalam Investment": "CHOLAFIN",
    "Cipla": "CIPLA",
    "Coal India": "COALINDIA",
    "Dabur India": "DABUR",
    "Divi's Labs": "DIVISLAB",
    "DLF": "DLF",
    "Dr Reddy's Labs": "DRREDDY",
    "Eicher Motors": "EICHERMOT",
    "GAIL": "GAIL",
    "Godrej Consumer": "GODREJCP",
    "Grasim": "GRASIM",
    "Havells India": "HAVELLS",
    "HCL Tech": "HCLTECH",
    "HDFC Bank": "HDFCBANK",
    "HDFC Life": "HDFCLIFE",
    "Hero MotoCorp": "HEROMOTOCO",
    "Hindalco": "HINDALCO",
    "Hindustan Unilever": "HINDUNILVR",
    "ICICI Bank": "ICICIBANK",
    "ICICI Lombard": "ICICIGI",
    "ICICI Prudential Life": "ICICIPRULI",
    "IndusInd Bank": "INDUSINDBK",
    "Infosys": "INFY",
    "InterGlobe Aviation (IndiGo)": "INDIGO",
    "ITC": "ITC",
    "JSW Steel": "JSWSTEEL",
    "Kotak Mahindra Bank": "KOTAKBANK",
    "L&T Finance": "LTF",
    "Larsen & Toubro": "LT",
    "LIC Housing Finance": "LICHSGFIN",
    "LTIMindtree": "LTIM",
    "Marico": "MARICO",
    "Maruti Suzuki": "MARUTI",
    "Mphasis": "MPHASIS",
    "Muthoot Finance": "MUTHOOTFIN",
    "Nestle India": "NESTLEIND",
    "NTPC": "NTPC",
    "Oil & Natural Gas Corp": "ONGC",
    "Page Industries": "PAGEIND",
    "Petronet LNG": "PETRONET",
    "PI Industries": "PIIND",
    "Pidilite Industries": "PIDILITIND",
    "Power Grid": "POWERGRID",
    "REC Ltd": "RECLTD",
    "Reliance Industries": "RELIANCE",
    "SBI Cards": "SBICARD",
    "SBI Life": "SBILIFE",
    "Shriram Finance": "SHRIRAMFIN",
    "Siemens": "SIEMENS",
    "State Bank of India": "SBIN",
    "Sun Pharma": "SUNPHARMA",
    "Tata Chemicals": "TATACHEM",
    "Tata Consumer": "TATACONSUM",
    "Tata Elxsi": "TATAELXSI",
    "Tata Motors": "TATAMOTORS",
    "Tata Power": "TATAPOWER",
    "Tata Steel": "TATASTEEL",
    "TCS": "TCS",
    "Tech Mahindra": "TECHM",
    "Titan": "TITAN",
    "Torrent Pharma": "TORNTPHARM",
    "Trent": "TRENT",
    "TVS Motor": "TVSMOTOR",
    "UltraTech Cement": "ULTRACEMCO",
    "UPL": "UPL",
    "Vedanta": "VEDL",
    "Wipro": "WIPRO",
    "Zee Entertainment": "ZEEL"
}